### ISSUE TITLE
Lumen 8 support

### ISSUE THREAD

**Issue by renky** [basicit/lumen-vendor-publish#12]
Laravel 8 and Lumen 8 are available
is it possible to only switch the composer requirements to 8.0 and create a new version of lumen-vendor-publish? I think it should be that easy...

**Comment by Kaishiyoku** [comment]
I already opened a pull request: https://github.com/laravelista/lumen-vendor-publish/pull/11

**Comment by renky** [comment]
ok, sorry - didn't have a look inside the pull requests... :) thx
