### ISSUE TITLE
Method Laravelista\LumenVendorPublish\VendorPublishCommand::handle() does not exist in lumen 5.5

### ISSUE THREAD

**Issue by permadiwibisono** [basicit/lumen-vendor-publish#4]
Hi @mabasic ,
There is new issue in Lumen 5.5 version.
Please merge PR, maybe it can solve.
https://github.com/laravelista/lumen-vendor-publish/pull/3

**Comment by RoseEnd** [comment]
I have the same problam.

**Comment by mabasic** [comment]
Merged PR. Solved in `2.1.0` release. Thanks for letting me know.
