### ISSUE TITLE
Nothing to publish for tag

### ISSUE THREAD

**Issue by ruturajmaniyar** [basicit/lumen-vendor-publish#5]
Hi,
After successfully Install this package, I run below command using terminal.
`php artisan ntcarfte:vendor:publish --provider "{provider class}"`

But This not working and getting error like below
**`Nothing to publish for tag [].`**

Kindly help me out here

Thanks

**Comment by psolom** [comment]
have the same issue

**Comment by mabasic** [comment]
Which Lumen version is this?

**Comment by psolom** [comment]
Lumen 5.5

I ran into this when I tried to publish assets for [laravel-phantomjs](https://github.com/iamalirezaj/laravel-phantomjs) package. See readme file.

And this is not the first time I get this error. It was a long time ago, so I don't remember which exact package caused an error.

**Comment by mabasic** [comment]
I will have to find some time to test this out.

**Comment by zishiguo** [comment]
@ruturajmaniyar I guess this problem. The package may use config_path  helper.  However, Lumen dont support. For example,  "prettus/l5-repository"
`    public function boot()
    {
        $this->publishes([
            __DIR__ . '/../../../resources/config/repository.php' => _config_path('repository.php')_
        ]);

        $this->mergeConfigFrom(__DIR__ . '/../../../resources/config/repository.php', 'repository');

        $this->loadTranslationsFrom(__DIR__ . '/../../../resources/lang', 'repository');
    }
`
in `\Prettus\Repository\Providers\RepositoryServiceProvider` Line 28.

Generally,  there are two methods as follows:

- copy  package config file  to  project "config" directory

-  require  "irazasyed/larasupport" again,  then,  use `php artisan vendor:pulish`
