### ISSUE TITLE
Lumen 6 Support please

### ISSUE THREAD

**Issue by royrakesh** [basicit/lumen-vendor-publish#6]

**Comment by gkimpson** [comment]
I also could use Lumen 6.x support for this as it seems to only work with 5.x and even then in the Composer response I get the following :
```
Package laravelista/lumen-vendor-publish is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by mabasic** [comment]
Hi guys, sorry about this. I was doing some cleaning and this package got overlooked.

I have un-abandoned it on packagist and Laravel 6 support is coming soon.

**Comment by gkimpson** [comment]
Thanks for the quick response that is much appreciated! Thank you 👍

**Comment by mabasic** [comment]
Added support for Lumen 6 :)

The package now follows Lumen framework versioning so that we have backward compatibility.

Use `"laravelista/lumen-vendor-publish": "^6.0"` to get Lumen 6 support or any other Lumen version starting from `5.1`.
